feat: add labels and annotations for storage classes
nutanix/helm pull request #123
Opened 2023-09-22 06:47 UTC by fad3t

Hello!

I would like to contribute a change that allows the customization of labels and annotations for the different storage classes. This also gives the option to set a custom name for the `VolumeSnapshotClass`.

Thanks,
Fred

2023-09-22 06:56 UTC, fad3t commented
This fixes #80

2023-09-25 06:52 UTC, tuxtof requested changes

2023-09-25 06:52 UTC, tuxtof commented on charts/nutanix-csi-storage/Chart.yaml
> +version: 2.7.0
ok to bump version to 2.6.5

2023-09-25 06:52 UTC, tuxtof commented on charts/nutanix-csi-storage/Chart.yaml
> +appVersion: "2.7.0"
driver will not change => 2.6.4

2023-09-25 06:52 UTC, tuxtof commented on charts/nutanix-csi-storage/Chart.yaml
> +    - Update Nutanix CSI driver to v2.7.0
don't change this line

2023-09-25 06:58 UTC, fad3t commented
Thanks, version has been adapted.

2023-09-25 07:08 UTC, merged