fix CSI driver v2.5.0 breaks mount of existing NFS dynamic PV
nutanix/helm pull request #47
Opened 2022-02-01 14:25 UTC by tuxtof

2022-02-01 22:00 UTC, subodh01 requested changes

2022-02-02 08:03 UTC, tuxtof commented on charts/nutanix-csi-storage/templates/ntnx-csi-rbac.yaml
> +  - apiGroups: [""]
interesting, what is the goal ?

2022-02-02 16:47 UTC, subodh01 approved these changes

2022-02-07 16:25 UTC, vnephologist approved these changes

2022-02-07 16:26 UTC, merged