Update README.md
nutanix/helm pull request #56
Opened 2022-06-01 20:37 UTC by chandru-tkc

Updated documentation to clarify prismEndpoint for users.

2022-06-02 06:49 UTC, tuxtof requested changes

2022-06-02 06:49 UTC, tuxtof commented on charts/nutanix-csi-storage/README.md
> +In the above command  `prismEndpoint` refers to the Prism Element cluster virtual ip address where k8s vms are running.
agree for the first part to clarify we are talking about Prism Element cluster virtual ip, but k8s vm can run anywhere not only on this cluster so let's replace by something like

`In the above command prismEndpoint refers to the Prism Element cluster virtual ip address where storage will be consumed.`

2022-06-02 06:49 UTC, tuxtof commented on charts/nutanix-csi-storage/README.md
> +In the above command  `prismEndpoint` refers to the Prism Element cluster virtual ip address where k8s vms are running.
same as above

2022-06-05 00:21 UTC, chandru-tkc commented on charts/nutanix-csi-storage/README.md
> +In the above command  `prismEndpoint` refers to the Prism Element cluster virtual ip address where k8s vms are running.
Sure thanks Chris, will update it

2022-06-05 00:24 UTC, chandru-tkc commented
Updated the documentation with correct statement

2022-06-06 06:37 UTC, tuxtof approved these changes

2022-06-06 06:37 UTC, merged